version: "3"

volumes:
  db_data:
  static_volume:
  media_volume:

services:
  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  star_burger:
    build: ./backend
    restart: always
    environment:
      - TZ=Europe/Moscow 
    ports:
      - 8000:8000
    depends_on:
      - node
    volumes:
          - static_volume:/star-burger/staticfiles
          - media_volume:/star-burger/media
    command: bash -c "python3 manage.py collectstatic --noinput --clear && python3 -m gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env

  node:
    build: ./frontend
    volumes:
      - static_volume:/star-burger/bundles
    ports:
      - 8080:8080
    command: bash -c "./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url='./'"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/opt/static
      - media_volume:/opt/media
    depends_on:
      - star_burger
      - node
