version: "3"

volumes:
  db_data:


services:
  postgresql:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  star_burger:
    build: ./backend
    restart: always
    environment:
      - TZ=Europe/Moscow 
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      - node
    volumes:
      - ./static:/star-burger/staticfiles
      - ./media:/star-burger/media
    command: bash -c "python3 manage.py collectstatic --noinput --clear && python3 manage.py migrate --noinput && python3 -m gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env

  node:
    build: ./frontend
    volumes:
      - ./static:/star-burger/bundles
    restart: always
    ports:
      - 8080:8080
    command: bash -c "./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url='./'"
  
