# Generated by Django 3.2.15 on 2023-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_rename_amount_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='OrderItem',
            name='product',
            field=models.ForeignKey(
                'Product',
                on_delete=models.CASCADE,
                blank=False,
                null=False
            ),
        ),

        migrations.AlterField(
            model_name='OrderItem',
            name='quantity',
            field=models.IntegerField(
                'количество',
                blank=False,
                null=False,
            ),
        ),
    ]
