# Generated by Django 3.2.15 on 2023-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230829_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Order',
            name='lastname',
            field=models.CharField(
                blank=False, 
                null=False,
                max_length=100, 
                verbose_name='адрес'
            ),
        ),
    ]
