# Generated by Django 3.2.15 on 2023-10-05 12:43

from django.db import migrations
from decimal import Decimal
from django.db.models import F

def populate_product_categories(apps, schema_editor):
    ProductCategory = apps.get_model('foodcartapp', 'ProductCategory')
    ProductCategory.objects.create(name='Category 1')
    ProductCategory.objects.create(name='Category 2')


def populate_products(apps, schema_editor):
    Product = apps.get_model('foodcartapp', 'Product')
    ProductCategory = apps.get_model('foodcartapp', 'ProductCategory')

    category_1 = ProductCategory.objects.get(name='Category 1')
    category_2 = ProductCategory.objects.get(name='Category 2')

    Product.objects.create(
        name='Cheeseburger',
        category=category_1,
        price=Decimal('5.99'),
        image='cheeseburger.jpg',
        special_status=True,
        description='A delicious cheeseburger with all the fixings.'
    )

    Product.objects.create(
        name='Margherita Pizza',
        category=category_2,
        price=Decimal('10.99'),
        image='margherita_pizza.jpg',
        special_status=False,
        description='A classic Margherita pizza with fresh tomatoes and basil.'
    )

    Product.objects.create(
        name='Chicken Alfredo Pasta',
        category=category_1,
        price=Decimal('12.99'),
        image='chicken_alfredo_pasta.jpg',
        special_status=True,
        description='Creamy chicken Alfredo pasta with garlic bread.'
    )

    # Add more products as needed

def populate_restaurants(apps, schema_editor):
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Restaurant.objects.create(
        name='Restaurant 1',
        address='Address 1',
        contact_phone='123-456-7890'
    )
    Restaurant.objects.create(
        name='Restaurant 2',
        address='Address 2',
        contact_phone='987-654-3210'
    )
    # Add more restaurants as needed

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230829_1724'),
    ]

    operations = [
        migrations.RunPython(populate_product_categories),
        migrations.RunPython(populate_products),
        migrations.RunPython(populate_restaurants),
    ]
