# Generated by Django 3.2.15 on 2023-10-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20231008_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coocking_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='готовится в'),
        ),
    ]
