# Generated by Django 3.2.15 on 2023-10-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_order_coocking_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coocking_by',
            new_name='cooking_by',
        ),
    ]
