# Generated by Django 3.2.15 on 2023-10-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_rename_coocking_by_order_cooking_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooking_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='готовится в'),
        ),
    ]
