# Generated by Django 3.2.15 on 2023-10-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20231006_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Картой'), ('CASH', 'Наличные')], default='CARD', max_length=6, verbose_name='метод оплаты'),
        ),
    ]
