# Generated by Django 3.2.15 on 2023-10-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Картой'), ('CASH', 'Наличные')], db_index=True, default='CARD', max_length=6, verbose_name='метод оплаты'),
        ),
    ]
