# Generated by Django 3.2.15 on 2023-10-07 17:56

from django.db import migrations
from foodcartapp.models import Product
from django.core.files.base import ContentFile
import requests

BASE_URL = 'https://github.com/devmanorg/star-burger-products/master/media/' 

def load_products(apps, schema_editor):
    Product = apps.get_model('foodcartapp', 'Product')  # Замените 'myapp' на имя вашего приложения

    product_data = [
        {
            "title": "Стейкхаус",
            "type": "Бургер",
            "price": "269",
            "img": "steak.jpg",
            "description": "Стейкхаус – это сочетание нашей фирменной, приготовленной на огне 100% говядины с ломтиками бекона и соусом «Барбекю», майонезом, листьями свежего салата, помидором и хрустящим луком на воздушной булочке, посыпанной кукурузной крошкой."
        },
        {
            "title": "Лонг Чизбургер",
            "type": "Бургер",
            "price": "219",
            "img": "long_chiz.jpg",
            "description": "Лонг Чизбургер – эталон в коллекции чизбургеров! Два приготовленных на огне бифштекса с двумя ломтиками слегка расплавленного сыра, хрустящими огурчиками, рубленым луком, горчицей и кетчупом на длинной подрумяненной булочке с кунжутом."
        },
        {
            "title": "Тройной Воппер",
            "type": "Бургер",
            "price": "369",
            "img": "triple_vopper.jpg",
            "description": "ВОППЕР® — это вкуснейшая приготовленная на огне 100% говядина с сочными помидорами, свежим нарезанным листовым салатом, густым майонезом, хрустящими маринованными огурчиками и свежим луком на нежной булочке с кунжутом."
        },
        {
            "title": "Беконайзер",
            "type": "Бургер",
            "price": "319",
            "img": "beconizer.jpg",
            "description": "Встречай самый внушительный бургер в коллекции Бургер Кинг. Много мяса, много бекона и много сыра - все, как ты любишь, и ничего лишнего!"
        },
        {
            "title": "Фиш Ролл",
            "type": "Ролл",
            "price": "199",
            "img": "fish_roll.jpg",
            "description": "Наш новый ролл с аппетитной котлеткой из филе белой рыбы, с фирменным соусом, маринованными огурчиками и хрустящим салатом. Легкое рыбное удовольствие!"
        },
        {
            "title": "Шримп Ролл",
            "type": "Ролл",
            "price": "209",
            "img": "shrimp_roll.jpg",
            "description": "Легкий ролл с нежными королевскими креветками в хрустящей панировке, свежий салат Айсберг и ломтик сыра в пшеничной лепешке под фирменным соусом «Кинг». Внимание! Блюдо содержит аллергены – морепродукты."
        }
    ]

    for product_info in product_data:
        img_url = BASE_URL + product_info['img']
        response = requests.get(img_url)
        if response.status_code == 200:
            product = Product.objects.create(
                name=product_info['title'],
                price=product_info['price'],
                description=product_info['description']
            )
            image_content = ContentFile(response.content)
            product.image.save(product_info['img'], image_content)
        else:
            print('error')
class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20231007_1750'),
    ]

    operations = [
        migrations.RunPython(load_products)
    ]
